const $=s=>document.querySelector(s),login=$('#login'),panel=$('#panel'),editor=$('#editor');let editing=null;
function message(text){$('#message').textContent=text;}
function isLoggedIn(){try{return sessionStorage.getItem('vg-demo-session')==='active';}catch{return false;}}
function showPanel(){login.hidden=true;panel.hidden=false;editor.hidden=true;draw();}
function draw(){ $('#summary').textContent=`${cars.length} vehículos · ${cars.filter(c=>c.status!=='sold').length} disponibles`;$('#admin-list').innerHTML=cars.map(c=>`<article class="admin-row"><img src="${escapeHtml(c.cover||c.photos[0])}" alt="${escapeHtml(c.name)}"><div class="info"><strong>${escapeHtml(c.name)}</strong><small>${escapeHtml(c.year)} · ${escapeHtml(c.price)} · ${c.status==='sold'?'Vendido':'Disponible'}</small></div><div class="admin-actions"><button data-edit="${escapeHtml(c.id)}">Editar</button><button data-delete="${escapeHtml(c.id)}">Eliminar</button></div></article>`).join('');}
function persist(next){try{localStorage.setItem(inventoryKey,JSON.stringify(next));cars=next;return true;}catch{message('No se pudieron guardar los cambios. Reduce la cantidad de fotografías o libera espacio en el navegador.');return false;}}
login.onsubmit=e=>{e.preventDefault();const f=new FormData(login);if(String(f.get('username')).trim().toLowerCase()!=='admin vg automotriz'||f.get('password')!=='VG automotriz'){message('Usuario o contraseña incorrectos.');return;}try{sessionStorage.setItem('vg-demo-session','active');}catch{}login.reset();message('Sesión de demostración iniciada.');showPanel();};
$('#logout').onclick=()=>{try{sessionStorage.removeItem('vg-demo-session');}catch{}panel.hidden=true;editor.hidden=true;login.hidden=false;message('Sesión cerrada.');};
function edit(id){editing=cars.find(c=>c.id===id)||null;editor.reset();$('#editor-title').textContent=editing?'Editar vehículo':'Agregar vehículo';if(editing)for(const key of ['name','year','type','price','km','trans','description','status'])editor.elements[key].value=editing[key]||(key==='status'?'available':'');panel.hidden=true;editor.hidden=false;editor.elements.name.focus();message('');}
$('#add').onclick=()=>edit(null);$('#cancel').onclick=()=>{showPanel();message('');};
$('#admin-list').onclick=e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.edit)edit(button.dataset.edit);if(button.dataset.delete&&confirm('¿Eliminar este vehículo de la demo?')){if(persist(cars.filter(c=>c.id!==button.dataset.delete))){draw();message('Vehículo eliminado de la demo.');}}};
$('#reset').onclick=()=>{if(confirm('¿Restaurar el inventario original? Se eliminarán los cambios de esta demo.'))if(persist(structuredClone(defaultCars))){draw();message('Inventario original restaurado.');}};
async function imageData(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Selecciona fotografías JPG, PNG o WebP.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/webp',.75);}
editor.onsubmit=async e=>{e.preventDefault();const submit=editor.querySelector('[type=submit]');submit.disabled=true;try{const f=new FormData(editor),files=[...editor.elements.photos.files];if(files.length>8)throw Error('Selecciona un máximo de 8 fotografías.');if(!editing&&!files.length)throw Error('Agrega al menos una fotografía.');const photos=files.length?await Promise.all(files.map(imageData)):editing.photos;const vehicle={...(editing||{}),id:editing?.id||crypto.randomUUID(),photos,cover:files.length?photos[0]:editing.cover};for(const key of ['name','year','type','price','km','trans','description','status'])vehicle[key]=String(f.get(key)).trim();if(editing&&['year','price','km','trans','type'].some(k=>vehicle[k]!==editing[k]))delete vehicle.specs;const next=editing?cars.map(c=>c.id===editing.id?vehicle:c):[...cars,vehicle];if(persist(next)){showPanel();message('Vehículo guardado. Puedes revisar el catálogo.');}}catch(error){message(error.message||'No fue posible guardar el vehículo.');}finally{submit.disabled=false;}};
if(isLoggedIn())showPanel();
