let filter='todos',query='',expanded=false,current=null,photo=0;const grid=document.querySelector('#grid'),drawer=document.querySelector('#drawer');
function render(){const list=cars.filter(c=>c.status!=='sold'&&(filter==='todos'||c.type===filter)&&c.name.toLowerCase().includes(query));document.querySelector('#count').textContent=list.length+' vehículos';grid.innerHTML=list.map((c,i)=>`<button class="car ${!expanded&&i>7?'hidden':''}" data-car="${escapeHtml(c.id)}"><span class="car-photo"><img src="${escapeHtml(c.cover||c.photos[0])}" alt="${escapeHtml(c.name)} ${escapeHtml(c.year)}" loading="lazy"><span class="status">DISPONIBLE</span></span><span class="car-info"><small>${escapeHtml(c.year)}</small><h3>${escapeHtml(c.name)}</h3><span class="meta"><span>${escapeHtml(c.km)}</span><span>${escapeHtml(c.trans)}</span></span><strong class="card-price">${escapeHtml(c.price)}</strong><span class="details-btn">VER DETALLES</span></span></button>`).join('');document.querySelector('#more').style.display=list.length>8?'block':'none';document.querySelector('#more').textContent=expanded?'Ver menos ↑':'Ver más vehículos ↓';grid.querySelectorAll('[data-car]').forEach(b=>b.onclick=()=>openCar(b.dataset.car))}
function showPhoto(){document.querySelector('#detail-img').src=current.photos[photo];document.querySelector('#detail-img').alt=current.name+' '+(photo+1);document.querySelector('#gallery-count').textContent=(photo+1)+' / '+current.photos.length;document.querySelector('.prev').style.display=current.photos.length>1?'block':'none';document.querySelector('.next').style.display=current.photos.length>1?'block':'none'}
function openCar(id){current=cars.find(c=>c.id===id);if(!current)return;photo=0;document.querySelector('#detail-year').textContent=current.year+' · '+current.km;document.querySelector('#detail-name').textContent=current.name;document.querySelector('#detail-price').textContent=current.price;document.querySelector('#detail-desc').textContent=current.description||'Consulta la información disponible de esta unidad. Las especificaciones completas se agregarán en cuanto VG Automotriz las confirme.';const specs=current.specs||[['#','Año',current.year],['▦','Tipo',current.type.toUpperCase()],['◴','Recorrido',current.km],['⚙','Transmisión',current.trans],['◇','Precio',current.price],['▱','Ubicación','Aguascalientes']];document.querySelector('#specs').innerHTML=specs.map(s=>`<div class="spec"><i>${s[0]}</i><small>${s[1]}</small><strong>${escapeHtml(s[2])}</strong></div>`).join('');const extras=current.extras||[];document.querySelector('#extras-wrap').style.display=extras.length?'block':'none';document.querySelector('#extras').innerHTML=extras.map(x=>`<span class="extra">${escapeHtml(x)}</span>`).join('');document.querySelector('#detail-wa').href='https://wa.me/524491059207?text='+encodeURIComponent('Hola, me interesa el '+current.name+' '+current.year+'. ¿Sigue disponible?');showPhoto();drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');document.body.classList.add('lock')}
function closeCar(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');document.body.classList.remove('lock')}
document.querySelector('#type-filter').onchange=e=>{filter=e.target.value;expanded=false;render()};document.querySelector('#search').oninput=e=>{query=e.target.value.trim().toLowerCase();expanded=false;render()};document.querySelector('#more').onclick=()=>{expanded=!expanded;render()};document.querySelector('.hero-car').onclick=()=>openCar('cupra');document.querySelector('.overlay').onclick=closeCar;document.querySelector('.close').onclick=closeCar;document.querySelector('.prev').onclick=()=>{photo=(photo-1+current.photos.length)%current.photos.length;showPhoto()};document.querySelector('.next').onclick=()=>{photo=(photo+1)%current.photos.length;showPhoto()};const header=document.querySelector('header'),menu=document.querySelector('.menu');
function closeMenu(){header.classList.remove('open');menu.setAttribute('aria-expanded','false');}
menu.onclick=()=>{menu.setAttribute('aria-expanded',String(header.classList.toggle('open')));};
header.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('click',e=>{if(!header.contains(e.target))closeMenu();});
window.addEventListener('resize',closeMenu);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCar();closeMenu()}});render();
