const cars=[
{id:'cupra',name:'Cupra Formentor',year:'2024',type:'suv',km:'4,800 km',trans:'Automática',price:'$600,000',cover:'assets/cupra-card.jpg',photos:['assets/cupra-1.jpg','assets/cupra-2.jpg','assets/cupra-3.jpg'],description:'El Cupra Formentor 2024, con solo 4,800 km y acabado en color blanco, combina diseño deportivo, tecnología y confort. Su interior espacioso incorpora asientos de piel, climatización bi-zona y conectividad pensada para disfrutar cada recorrido.',specs:[['#','Publicación','#4774397'],['◇','Marca','Cupra'],['▱','Modelo','Formentor'],['▤','Versión','Estándar'],['▦','Subtipo','Camioneta SUV'],['◴','Recorrido','4,800 km'],['≋','Climatización','Climatizador bi-zona'],['⚙','Tracción','AWD'],['◉','Color','Blanco'],['□','Vidrios','Eléctricos'],['⚙','Transmisión','Automática'],['◉','Dirección','Hidráulica'],['▰','Tapizado','Piel'],['▥','Combustible','Gasolina']],extras:['Acepto vehículo','Único dueño']},
{id:'mercedes',name:'Mercedes-Benz CLA',year:'Consultar',type:'sedan',km:'Consultar',trans:'Automática',price:'Consultar',cover:'assets/catalog-mercedes-v2.jpg',photos:['assets/mercedes-cla-1.jpg','assets/mercedes-cla-2.jpg'],description:'Mercedes-Benz en color plata. Solicita año, kilometraje, precio y ficha completa directamente con VG Automotriz.'},
{id:'volvo',name:'Volvo EX30',year:'2024',type:'suv',km:'Consultar',trans:'Automática',price:'Consultar',cover:'assets/catalog-volvo-v2.jpg',photos:['assets/volvo-1-clean.jpg','assets/volvo-2-clean.jpg'],description:'Galería tomada del material original proporcionado por VG Automotriz. Solicita disponibilidad y ficha completa por WhatsApp.'},
{id:'taos',name:'Volkswagen Taos Highline',year:'2023',type:'suv',km:'70,500 km',trans:'Consultar',price:'$410,000',cover:'assets/catalog-taos-v2.jpg',photos:['assets/taos-1-clean.jpg','assets/taos-2-clean.jpg','assets/taos-3-clean.jpg'],description:'Volkswagen Taos Highline 2023 en color gris. Consulta equipamiento, condiciones y disponibilidad directamente con VG Automotriz.'},
{id:'corolla',name:'Toyota Corolla',year:'2024',type:'sedan',km:'Consultar',trans:'Automática',price:'Consultar',cover:'assets/catalog-corolla-v2.jpg',photos:['assets/corolla-1-clean.jpg','assets/corolla-2-clean.jpg','assets/corolla-3-clean.jpg'],description:'Toyota Corolla 2024 con galería del material original de la agencia. Solicita precio y ficha completa por WhatsApp.'},
{id:'frontier',name:'Nissan Frontier XE',year:'2021',type:'pickup',km:'152,000 km',trans:'Consultar',price:'$330,000',cover:'assets/catalog-frontier-v2.jpg',photos:['assets/frontier-hd-1.jpg','assets/frontier-hd-2.jpg'],description:'Nissan Frontier XE 2021 en color blanco. Consulta condiciones, equipamiento y disponibilidad.'}
];
let filter='todos',query='',expanded=false,current=null,photo=0;const grid=document.querySelector('#grid'),drawer=document.querySelector('#drawer');
function render(){const list=cars.filter(c=>(filter==='todos'||c.type===filter)&&c.name.toLowerCase().includes(query));document.querySelector('#count').textContent=list.length+' vehículos';grid.innerHTML=list.map((c,i)=>`<button class="car ${!expanded&&i>7?'hidden':''}" data-car="${c.id}"><span class="car-photo"><img src="${c.cover||c.photos[0]}" alt="${c.name} ${c.year}" loading="lazy"><span class="status">DISPONIBLE</span></span><span class="car-info"><small>${c.year}</small><h3>${c.name}</h3><span class="meta"><span>${c.km}</span><span>${c.trans}</span></span><strong class="card-price">${c.price}</strong><span class="details-btn">VER DETALLES</span></span></button>`).join('');document.querySelector('#more').style.display=list.length>8?'block':'none';document.querySelector('#more').textContent=expanded?'Ver menos ↑':'Ver más vehículos ↓';grid.querySelectorAll('[data-car]').forEach(b=>b.onclick=()=>openCar(b.dataset.car))}
function showPhoto(){document.querySelector('#detail-img').src=current.photos[photo];document.querySelector('#detail-img').alt=current.name+' '+(photo+1);document.querySelector('#gallery-count').textContent=(photo+1)+' / '+current.photos.length;document.querySelector('.prev').style.display=current.photos.length>1?'block':'none';document.querySelector('.next').style.display=current.photos.length>1?'block':'none'}
function openCar(id){current=cars.find(c=>c.id===id);photo=0;document.querySelector('#detail-year').textContent=current.year+' · '+current.km;document.querySelector('#detail-name').textContent=current.name;document.querySelector('#detail-price').textContent=current.price;document.querySelector('#detail-desc').textContent=current.description||'Consulta la información disponible de esta unidad. Las especificaciones completas se agregarán en cuanto VG Automotriz las confirme.';const specs=current.specs||[['#','Año',current.year],['▦','Tipo',current.type.toUpperCase()],['◴','Recorrido',current.km],['⚙','Transmisión',current.trans],['◇','Precio',current.price],['▱','Ubicación','Aguascalientes']];document.querySelector('#specs').innerHTML=specs.map(s=>`<div class="spec"><i>${s[0]}</i><small>${s[1]}</small><strong>${s[2]}</strong></div>`).join('');const extras=current.extras||[];document.querySelector('#extras-wrap').style.display=extras.length?'block':'none';document.querySelector('#extras').innerHTML=extras.map(x=>`<span class="extra">${x}</span>`).join('');document.querySelector('#detail-wa').href='https://wa.me/524491059207?text='+encodeURIComponent('Hola, me interesa el '+current.name+' '+current.year+'. ¿Sigue disponible?');showPhoto();drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');document.body.classList.add('lock')}
function closeCar(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');document.body.classList.remove('lock')}
document.querySelector('#type-filter').onchange=e=>{filter=e.target.value;expanded=false;render()};document.querySelector('#search').oninput=e=>{query=e.target.value.trim().toLowerCase();expanded=false;render()};document.querySelector('#more').onclick=()=>{expanded=!expanded;render()};document.querySelector('.hero-car').onclick=()=>openCar('cupra');document.querySelector('.overlay').onclick=closeCar;document.querySelector('.close').onclick=closeCar;document.querySelector('.prev').onclick=()=>{photo=(photo-1+current.photos.length)%current.photos.length;showPhoto()};document.querySelector('.next').onclick=()=>{photo=(photo+1)%current.photos.length;showPhoto()};document.querySelector('.menu').onclick=()=>document.querySelector('header').classList.toggle('open');document.addEventListener('keydown',e=>{if(e.key==='Escape')closeCar()});render();
