const defaultCars=[
{id:'cupra',name:'Cupra Formentor',year:'2024',type:'suv',km:'4,800 km',trans:'Automática',price:'$600,000',cover:'assets/cupra-card.jpg',photos:['assets/cupra-1.jpg','assets/cupra-2.jpg','assets/cupra-3.jpg'],description:'El Cupra Formentor 2024, con solo 4,800 km y acabado en color blanco, combina diseño deportivo, tecnología y confort. Su interior espacioso incorpora asientos de piel, climatización bi-zona y conectividad pensada para disfrutar cada recorrido.',specs:[['#','Publicación','#4774397'],['◇','Marca','Cupra'],['▱','Modelo','Formentor'],['▤','Versión','Estándar'],['▦','Subtipo','Camioneta SUV'],['◴','Recorrido','4,800 km'],['≋','Climatización','Climatizador bi-zona'],['⚙','Tracción','AWD'],['◉','Color','Blanco'],['□','Vidrios','Eléctricos'],['⚙','Transmisión','Automática'],['◉','Dirección','Hidráulica'],['▰','Tapizado','Piel'],['▥','Combustible','Gasolina']],extras:['Acepto vehículo','Único dueño']},
{id:'mercedes',name:'Mercedes-Benz CLA',year:'Consultar',type:'sedan',km:'Consultar',trans:'Automática',price:'Consultar',cover:'assets/catalog-mercedes-v2.jpg',photos:['assets/mercedes-cla-1.jpg','assets/mercedes-cla-2.jpg'],description:'Mercedes-Benz en color plata. Solicita año, kilometraje, precio y ficha completa directamente con VG Automotriz.'},
{id:'volvo',name:'Volvo EX30',year:'2024',type:'suv',km:'Consultar',trans:'Automática',price:'Consultar',cover:'assets/catalog-volvo-v2.jpg',photos:['assets/volvo-1-clean.jpg','assets/volvo-2-clean.jpg'],description:'Galería tomada del material original proporcionado por VG Automotriz. Solicita disponibilidad y ficha completa por WhatsApp.'},
{id:'taos',name:'Volkswagen Taos Highline',year:'2023',type:'suv',km:'70,500 km',trans:'Consultar',price:'$410,000',cover:'assets/catalog-taos-v2.jpg',photos:['assets/taos-1-clean.jpg','assets/taos-2-clean.jpg','assets/taos-3-clean.jpg'],description:'Volkswagen Taos Highline 2023 en color gris. Consulta equipamiento, condiciones y disponibilidad directamente con VG Automotriz.'},
{id:'corolla',name:'Toyota Corolla',year:'2024',type:'sedan',km:'Consultar',trans:'Automática',price:'Consultar',cover:'assets/catalog-corolla-v2.jpg',photos:['assets/corolla-1-clean.jpg','assets/corolla-2-clean.jpg','assets/corolla-3-clean.jpg'],description:'Toyota Corolla 2024 con galería del material original de la agencia. Solicita precio y ficha completa por WhatsApp.'},
{id:'frontier',name:'Nissan Frontier XE',year:'2021',type:'pickup',km:'152,000 km',trans:'Consultar',price:'$330,000',cover:'assets/catalog-frontier-v2.jpg',photos:['assets/frontier-hd-1.jpg','assets/frontier-hd-2.jpg'],description:'Nissan Frontier XE 2021 en color blanco. Consulta condiciones, equipamiento y disponibilidad.'}
];
const inventoryKey='vg-demo-inventory-v1';
let cars=structuredClone(defaultCars);
try { const saved=JSON.parse(localStorage.getItem(inventoryKey)); if(Array.isArray(saved)&&saved.every(c=>c&&typeof c.name==='string'&&Array.isArray(c.photos)&&c.photos.length)) cars=saved; } catch {}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
